<script>
    function fun(){
        return new Promise((resp,rej)=>{
            setTimeout(()=>{
                const err=true;
                if(!err){
                    console.log("thank you juice");
                    resp();
                }else{
                    console.log("sorry im busy");
                    rej();
                }
            },3000)
        })
    }

fun().then(()=>{
console.log("im getting executed because promise fulfilled")
}).catch(()=>{
    console.log("error because sagar is not picking the phone")
})

</script>